Feat/rolluxtestnet
Uno-Re/SSIP-SSRP-contracts pull request #87
Opened 2024-05-09 14:22 UTC by ThimSouza

2024-06-26 20:39 UTC, claudiovb requested changes
Partial Review 1

2024-07-18 22:43 UTC, ThimSouza reviewed
Reviewed with Claudio

2024-07-19 15:39 UTC, ThimSouza reviewed
removed unused files and folders from github

2024-08-07 19:36 UTC, Potolski commented on package-lock.json
Remove this file. We already have yarn.lock and having both will most likely cause problems

2024-09-05 17:30 UTC, merged